name: CI

on:
  push:
    branches: [ main, milestone/** ]
  pull_request:
    branches: [ main, milestone/** ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
      - run: npm install
      - run: npm build

  test:
    runs-on: ubuntu-latest
    needs: [build] 
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
      - run: npm install
      - run: npm test
    
  coverage:
      runs-on: ubuntu-latest
      needs: [build] 
      if: "!contains(github.event.head_commit.message, '[skip ci]')"
      steps:
          - uses: actions/checkout@v1
          - uses: artiomtr/jest-coverage-report-action@v2.0-rc.5
            with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                threshold: 95
                test-script: npm run test:coverage
          - name: Upload coverage report
            uses: actions/upload-artifact@v2
            with:
              name: coverage
              path: |
                ${{ github.workspace }}/coverage
  
  sonar-report:
    runs-on: ubuntu-latest
    needs: [coverage]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Download coverage artifact
        uses: actions/download-artifact@v2
        with:
          name: coverage
          path: coverage
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.sources="app/src"
            -Dsonar.tests="app/test"
            -Dsonar.javascript.lcov.reportPaths="coverage/lcov.info"
            -Dsonar.organization=ferrgo
            -Dsonar.projectKey=ferrgo_ccca